<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://org.apache.axis2/xsd" xmlns:ns="http://ws.service.qpid.carbon.wso2.org" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" targetNamespace="http://ws.service.qpid.carbon.wso2.org">
    <wsdl:documentation>QpidAdminService</wsdl:documentation>
    <wsdl:types>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://ws.service.qpid.carbon.wso2.org">
            <xs:element name="getAccessKey">
                <xs:complexType>
                    <xs:sequence />
                </xs:complexType>
            </xs:element>
            <xs:element name="getAccessKeyResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="return" nillable="true" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="getAccessKeyRequest">
        <wsdl:part name="parameters" element="ns:getAccessKey" />
    </wsdl:message>
    <wsdl:message name="getAccessKeyResponse">
        <wsdl:part name="parameters" element="ns:getAccessKeyResponse" />
    </wsdl:message>
    <wsdl:portType name="QpidAdminServicePortType">
        <wsdl:operation name="getAccessKey">
            <wsdl:input message="ns:getAccessKeyRequest" wsaw:Action="urn:getAccessKey" />
            <wsdl:output message="ns:getAccessKeyResponse" wsaw:Action="urn:getAccessKeyResponse" />
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QpidAdminServiceSoap11Binding" type="ns:QpidAdminServicePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl:operation name="getAccessKey">
            <soap:operation soapAction="urn:getAccessKey" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="QpidAdminServiceSoap12Binding" type="ns:QpidAdminServicePortType">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl:operation name="getAccessKey">
            <soap12:operation soapAction="urn:getAccessKey" style="document" />
            <wsdl:input>
                <soap12:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="QpidAdminServiceHttpBinding" type="ns:QpidAdminServicePortType">
        <http:binding verb="POST" />
        <wsdl:operation name="getAccessKey">
            <http:operation location="getAccessKey" />
            <wsdl:input>
                <mime:content type="text/xml" part="parameters" />
            </wsdl:input>
            <wsdl:output>
                <mime:content type="text/xml" part="parameters" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="QpidAdminService">
        <wsdl:port name="QpidAdminServiceHttpsSoap11Endpoint" binding="ns:QpidAdminServiceSoap11Binding">
            <soap:address location="https://111.223.147.235:9443/services/QpidAdminService.QpidAdminServiceHttpsSoap11Endpoint/" />
        </wsdl:port>
        <wsdl:port name="QpidAdminServiceHttpsSoap12Endpoint" binding="ns:QpidAdminServiceSoap12Binding">
            <soap12:address location="https://111.223.147.235:9443/services/QpidAdminService.QpidAdminServiceHttpsSoap12Endpoint/" />
        </wsdl:port>
        <wsdl:port name="QpidAdminServiceHttpsEndpoint" binding="ns:QpidAdminServiceHttpBinding">
            <http:address location="https://111.223.147.235:9443/services/QpidAdminService.QpidAdminServiceHttpsEndpoint/" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>